apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    target: 80
  selector:
    app: nginx
  type: NodePort