# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-world
# spec:
#   replicas: 1
#     selector:
#       matchLabels:
#         app: hello-world
#   template:
#     metadata:
#       labels:
#         app: hello-world
#     spec:
#       containers:
#       - name: hello-world
#       image: nginx:latest
#       ports:
#       - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 8080
