# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-world
# spec:
#   selector:
#     app: hello-world
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080